/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.fabricagalton.vista;

import com.mycompany.fabricagalton.modelo.Bola;
import com.mycompany.fabricagalton.modelo.TableroGalton;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Rubén
 */
public class VistaTableroGalton extends javax.swing.JDialog {

   private TableroGalton tableroGalton ;
   private JPanel paneles[];
   private JLabel celdas[][];
   private JLabel depositos[];
   int nBolas ;
   
    public VistaTableroGalton(TableroGalton tableroGlton,int nBolas) {
        initComponents();
        this.tableroGalton = tableroGlton;
        this.nBolas = nBolas;
        construccionTablero();
    }
    
    private void construccionTablero(){
        int filas = tableroGalton.getNFilas();
        panelTablero.setLayout(new GridLayout(filas,1));
        paneles = new JPanel[filas];
        celdas = new JLabel[filas][];
        for (int i = 0; i < filas; i++) {
            paneles[i] = new JPanel();
            celdas[i] = new JLabel[i+1];
            for (int j = 0; j < i+1; j++) {
                celdas [i][j] = this.celdaVacia();
                FlowLayout flowLayout = new FlowLayout();
                flowLayout.setHgap(50);
                paneles[i].setLayout(flowLayout);
                paneles[i].setBackground(Color.lightGray);
                paneles[i].add(celdas[i][j]);
            }
            this.panelTablero.add(paneles[i]);
        }
        depositos = new JLabel[filas+1];
        ((FlowLayout)panelDepositos.getLayout()).setHgap(50);
        for (int i = 0; i < filas+1; i++) {
            depositos[i]= new JLabel("0");
            depositos[i].setHorizontalAlignment(JLabel.CENTER);
            depositos[i].setVerticalAlignment(JLabel.CENTER);
            depositos[i].setPreferredSize(new Dimension(40,40));
            panelDepositos.add(depositos[i]);
        }
        this.setSize(1200,800);
    }
    
    private JLabel celdaVacia (){
        JLabel celda = new JLabel();
        celda.setLayout(new BorderLayout());
        celda.setPreferredSize(new Dimension (40,40));
        celda.setHorizontalAlignment(JLabel.CENTER);
        celda.setVerticalAlignment(JLabel.CENTER);
        celda.setOpaque(true);
        celda.setBackground(Color.white);
        return celda;
    }
    private void dibujarCeldaBola(JLabel celda,Bola bola){
        vaciarCelda(celda);
        if(bola != null){
            int indice = bola.getNumero()%5;
            celda.setIcon(new ImageIcon("imagenes\\bola"+indice+".jpg"));
            JLabel etiquetaTexto = new JLabel (bola.getNumero()+"");
            etiquetaTexto.setHorizontalAlignment(JLabel.CENTER);
            etiquetaTexto.setVerticalAlignment(JLabel.CENTER);
            celda.add(etiquetaTexto);
            
        }
    }
    
    public void actualizarDibujoTablero(){
        int filas = tableroGalton.getNFilas();
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < i+1; j++) {
                
                dibujarCeldaBola(celdas[i][j],tableroGalton.getContenidoCelda(i, j));
                this.repaint();
            }
        }
        for (int i = 0; i < depositos.length; i++) {
            depositos[i].setText(tableroGalton.getDeposito(i).size()+"");
        }
    }
    
    private void vaciarCelda(JLabel celda){
        celda.setIcon(null);
        celda.removeAll();
    }
    private void vaciarDepositos() {
        tableroGalton.iniciarDepositos(depositos.length);
        for(int i=0;i<depositos.length;i++) {
            depositos[i].setText("0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablero = new javax.swing.JPanel();
        panelBoton = new javax.swing.JPanel();
        btnLanzarBolas = new javax.swing.JButton();
        panelDepositos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTablero.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        getContentPane().add(panelTablero, java.awt.BorderLayout.CENTER);

        panelBoton.setBackground(new java.awt.Color(255, 255, 153));

        btnLanzarBolas.setText("Lanzar Bolas");
        btnLanzarBolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarBolasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonLayout = new javax.swing.GroupLayout(panelBoton);
        panelBoton.setLayout(panelBotonLayout);
        panelBotonLayout.setHorizontalGroup(
            panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBotonLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnLanzarBolas)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelBotonLayout.setVerticalGroup(
            panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBotonLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnLanzarBolas)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(panelBoton, java.awt.BorderLayout.PAGE_START);

        panelDepositos.setBackground(new java.awt.Color(153, 255, 204));
        getContentPane().add(panelDepositos, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanzarBolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarBolasActionPerformed
        vaciarDepositos();
        tableroGalton.setVistaTableroGalton(this);
        Bola bolas[] = new Bola[nBolas];
        for(int i=0;i<nBolas;i++) {
            bolas[i] = new Bola(i+1,tableroGalton);
        }
        Thread hilos[] = new Thread[nBolas];
        for(int i=0;i<nBolas;i++) {
            hilos[i] = new Thread(bolas[i]);
            hilos[i].start();
        }
    }//GEN-LAST:event_btnLanzarBolasActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanzarBolas;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelDepositos;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables
}
